# Generated by Django 3.2 on 2021-04-24 03:25

from django.db import migrations, models # pragma: no cover
import django.db.models.deletion # pragma: no cover


class Migration(migrations.Migration): # pragma: no cover

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('user_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='DATAHACK', max_length=30)),
                ('email_address', models.CharField(default='', max_length=200)),
                ('short_tax_rate', models.FloatField(default=0.0)),
                ('long_tax_rate', models.FloatField(default=0.0)),
                ('invest_horizon', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('purchase_price', models.FloatField(default=-1.0)),
                ('target_price', models.FloatField(default=0.0)),
                ('expect_return_rate', models.FloatField(default=0.0)),
                ('purchase_date', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.userprofile')),
            ],
        ),
    ]
