# Generated by Django 2.2 on 2021-05-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210424_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='_sended',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_notify',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='opportunity_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sell_notify',
            field=models.FloatField(default=0.0),
        ),
    ]
