# Generated by Django 2.1.3 on 2018-11-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='adress',
            new_name='address',
        ),
    ]
